// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhN9A-PNo2oQ416AN7jpDesn8WCLv1UQ',
    appId: '1:308502063703:web:33210eea37d67362fbd112',
    messagingSenderId: '308502063703',
    projectId: 'job-timer-project',
    authDomain: 'job-timer-project.firebaseapp.com',
    storageBucket: 'job-timer-project.appspot.com',
    measurementId: 'G-8K0ED409ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJwRHKvh6YkjiCJEi3lfj7DbCwu2rj_M4',
    appId: '1:308502063703:android:68eda1903212a6b6fbd112',
    messagingSenderId: '308502063703',
    projectId: 'job-timer-project',
    storageBucket: 'job-timer-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGNn8o2ubrdGqdAoDBYGup8vz-AOniWE',
    appId: '1:308502063703:ios:bba2c83cb25e4304fbd112',
    messagingSenderId: '308502063703',
    projectId: 'job-timer-project',
    storageBucket: 'job-timer-project.appspot.com',
    iosClientId: '308502063703-05r317c6em7rt27ufe2sjuqnil5erco2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
